import { Issue } from "./002_gameConfig";

// 英語60本 / 日本語240本（合計300本）  ※英語:日本語 ≒ 2:8
// romaji はローマ字判定用にそのまま英字・ひらがな読みを格納

const EN_SHORT: Issue[] = [
  { text: "practice makes perfect", romaji: "practice makes perfect" },
  { text: "stay calm and type on", romaji: "stay calm and type on" },
  { text: "home row first", romaji: "home row first" },
  { text: "keep your eyes on the screen", romaji: "keep your eyes on the screen" },
  { text: "accuracy before speed", romaji: "accuracy before speed" },
  { text: "touch typing forever", romaji: "touch typing forever" },
  {
    text: "rapid iteration beats premature optimization",
    romaji: "rapid iteration beats premature optimization",
  },
  { text: "measure twice cut once", romaji: "measure twice cut once" },
  { text: "clean code pays dividends", romaji: "clean code pays dividends" },
  { text: "refactoring is an investment", romaji: "refactoring is an investment" },
  { text: "naming things is hard", romaji: "naming things is hard" },
  { text: "bugs hide in assumptions", romaji: "bugs hide in assumptions" },
  { text: "good posture prevents fatigue", romaji: "good posture prevents fatigue" },
  { text: "short breaks help focus", romaji: "short breaks help focus" },
  { text: "steady rhythm beats bursts", romaji: "steady rhythm beats bursts" },
  { text: "muscle memory grows daily", romaji: "muscle memory grows daily" },
  { text: "relaxed shoulders steady hands", romaji: "relaxed shoulders steady hands" },
  { text: "breathe and keep typing", romaji: "breathe and keep typing" },
  { text: "keyboard shortcuts save time", romaji: "keyboard shortcuts save time" },
  { text: "read before you type", romaji: "read before you type" },
  { text: "understand structure first", romaji: "understand structure first" },
  { text: "copying code requires meaning", romaji: "copying code requires meaning" },
  { text: "consistency beats luck", romaji: "consistency beats luck" },
  { text: "celebrate small wins", romaji: "celebrate small wins" },
  { text: "ship small changes quickly", romaji: "ship small changes quickly" },
  { text: "optimize after it works", romaji: "optimize after it works" },
  { text: "plan the work then work the plan", romaji: "plan the work then work the plan" },
  { text: "slow is smooth smooth is fast", romaji: "slow is smooth smooth is fast" },
  { text: "focus on the next key", romaji: "focus on the next key" },
  { text: "eyes forward fingers down", romaji: "eyes forward fingers down" },
  { text: "learn once remember forever", romaji: "learn once remember forever" },
  { text: "repeat to build speed", romaji: "repeat to build speed" },
  { text: "good habits beat talent", romaji: "good habits beat talent" },
  { text: "type what you think ahead", romaji: "type what you think ahead" },
  { text: "predict the next letter", romaji: "predict the next letter" },
  { text: "smooth strokes beat force", romaji: "smooth strokes beat force" },
  { text: "count mistakes learn patterns", romaji: "count mistakes learn patterns" },
  { text: "stretch your hands often", romaji: "stretch your hands often" },
  { text: "hydrate and keep typing", romaji: "hydrate and keep typing" },
  { text: "warm up before a session", romaji: "warm up before a session" },
  { text: "precision leads to speed", romaji: "precision leads to speed" },
  { text: "train both hands evenly", romaji: "train both hands evenly" },
  { text: "light touch saves energy", romaji: "light touch saves energy" },
  { text: "delete fear of backspace", romaji: "delete fear of backspace" },
  { text: "embrace consistent posture", romaji: "embrace consistent posture" },
  { text: "aim for rhythm not rush", romaji: "aim for rhythm not rush" },
  { text: "master the space bar", romaji: "master the space bar" },
  { text: "shift with confidence", romaji: "shift with confidence" },
  { text: "let accuracy be your coach", romaji: "let accuracy be your coach" },
  { text: "listen to the cadence", romaji: "listen to the cadence" },
  { text: "finish the sentence cleanly", romaji: "finish the sentence cleanly" },
  { text: "train accuracy then add pace", romaji: "train accuracy then add pace" },
  { text: "hear the rhythm of keys", romaji: "hear the rhythm of keys" },
  { text: "anticipate the next word", romaji: "anticipate the next word" },
  { text: "hands hover not hammer", romaji: "hands hover not hammer" },
  { text: "rest thumbs near the space bar", romaji: "rest thumbs near the space bar" },
  { text: "align your wrists straight", romaji: "align your wrists straight" },
  { text: "pivot from elbows lightly", romaji: "pivot from elbows lightly" },
  { text: "aim for smooth repetition", romaji: "aim for smooth repetition" },
  { text: "short drills beat long slogs", romaji: "short drills beat long slogs" },
  { text: "errors are data not shame", romaji: "errors are data not shame" },
  { text: "let cadence guide your speed", romaji: "let cadence guide your speed" },
  { text: "stay loose in the shoulders", romaji: "stay loose in the shoulders" },
  { text: "micro rests prevent macro pain", romaji: "micro rests prevent macro pain" },
  { text: "steady tempo builds mastery", romaji: "steady tempo builds mastery" },
  { text: "challenge hard words daily", romaji: "challenge hard words daily" },
  { text: "practice blindfold home row", romaji: "practice blindfold home row" },
];

// 日本語 240
const JA_SHORT: Issue[] = [
  { text: "明日は明日の風が吹く", romaji: "あしたはあしたのかぜがふく" },
  { text: "早起きは三文の得", romaji: "はやおきはさんもんのとく" },
  { text: "石の上にも三年", romaji: "いしのうえにもさんねん" },
  { text: "初心忘るべからず", romaji: "しょしんわするべからず" },
  { text: "継続は力なり", romaji: "けいぞくはちからなり" },
  { text: "急がば回れ", romaji: "いそがばまわれ" },
  { text: "習うより慣れろ", romaji: "ならうよりなれろ" },
  { text: "百聞は一見にしかず", romaji: "ひゃくぶんはいっけんにしかず" },
  { text: "七転び八起き", romaji: "ななころびやおき" },
  { text: "雨降って地固まる", romaji: "あめふってじかたまる" },
  { text: "光陰矢の如し", romaji: "こういんやのごとし" },
  { text: "手は口ほどに物を言う", romaji: "てはくちほどにものをいう" },
  { text: "背筋を伸ばして深呼吸", romaji: "せすじをのばしてしんこきゅう" },
  { text: "指先の力を抜いて打つ", romaji: "ゆびさきのちからをぬいてうつ" },
  { text: "姿勢を正せば速度も伸びる", romaji: "しせいをただせばそくどものびる" },
  { text: "短い練習を毎日続ける", romaji: "みじかいれんしゅうをまいにちつづける" },
  { text: "焦らず落ち着いて入力する", romaji: "あせらずおちついてにゅうりょくする" },
  { text: "視線は画面に指は自然に", romaji: "しせんはがめんにゆびはしぜんに" },
  { text: "誤字は学びの種になる", romaji: "ごじはまなびのたねになる" },
  { text: "深呼吸で肩の力を抜こう", romaji: "しんこきゅうでかたのちからをぬこう" },
  { text: "打鍵音はリズムの合図", romaji: "だけんおんはりずむのあいず" },
  { text: "速さよりまず正確さ", romaji: "はやさよりまずせいかくさ" },
  { text: "手首は浮かせず安定させる", romaji: "てくびはうかせずあんていさせる" },
  { text: "ホームポジションを守る", romaji: "ほーむぽじしょんをまもる" },
  { text: "指を大きく動かさない", romaji: "ゆびをおおきくうごかさない" },
  { text: "スペースキーも親指で均等に", romaji: "すぺーすきーもおやゆびできんとうに" },
  { text: "数字列も少しずつ慣れよう", romaji: "すうじれつもすこしずつなれよう" },
  { text: "母音を意識してリズムを取る", romaji: "ぼいんをいしきしてりずむをとる" },
  { text: "小指のストレッチを忘れずに", romaji: "こゆびのすとれっちをわすれずに" },
  { text: "机と椅子の高さを合わせる", romaji: "つくえといすのたかさをあわせる" },
  { text: "手元を見ない勇気を持つ", romaji: "てもとをみないゆうきをもつ" },
  { text: "打鍵前に文字列を先読みする", romaji: "だけんまえにもじれつをさきよみする" },
  { text: "打ち終わったら肩を回す", romaji: "うちおわったらかたをまわす" },
  { text: "音読しながらリズムを作る", romaji: "おんどくしながらりずむをつくる" },
  { text: "長文は段落ごとに区切って覚える", romaji: "ちょうぶんはだんらくごとにくぎっておぼえる" },
  { text: "一文字ずつ丁寧に置いていく", romaji: "いちもじずつていねいにおいていく" },
  { text: "疲れたら一旦手を止める", romaji: "つかれたらいったんてをとめる" },
  { text: "深夜より朝の方が集中できる", romaji: "しんやよりあさのほうがしゅうちゅうできる" },
  { text: "音楽はリズム系が相性がいい", romaji: "おんがくはりずむけいがあいしょうがいい" },
  { text: "手汗は布で軽く拭き取る", romaji: "てあせはぬのでかるくふきとる" },
  { text: "背もたれに頼りすぎない", romaji: "せもたれにたよりすぎない" },
  { text: "画面の文字サイズを整える", romaji: "がめんのもじさいずをととのえる" },
  { text: "指の移動距離を意識する", romaji: "ゆびのいどうきょりをいしきする" },
  { text: "まずはゆっくり正確に", romaji: "まずはゆっくりせいかくに" },
  { text: "身体が覚えるまで繰り返す", romaji: "からだがおぼえるまでくりかえす" },
  { text: "毎日五分でも続けること", romaji: "まいにちごふんでもつづけること" },
  { text: "休むのも練習のうち", romaji: "やすむのもれんしゅうのうち" },
  { text: "失敗は成功のもと", romaji: "しっぱいはせいこうのもと" },
  { text: "胸を張って前を向く", romaji: "むねをはってまえをむく" },
  { text: "指の腹でキーを押す", romaji: "ゆびのはらできーをおす" },
  { text: "段落ごとに深呼吸する", romaji: "だんらくごとにしんこきゅうする" },
  { text: "猫背にならないよう注意", romaji: "ねこぜにならないようちゅうい" },
  { text: "ひらがな入力でも正確に", romaji: "ひらがないりょくでもせいかくに" },
  { text: "目はやさしく画面を追う", romaji: "めはやさしくがめんをおう" },
  { text: "軽いタッチで速度が上がる", romaji: "かるいたっちでそくどがあがる" },
  { text: "腕の重さを机に預けすぎない", romaji: "うでのおもさをつくえにあずけすぎない" },
  { text: "手首の角度をフラットに保つ", romaji: "てくびのかくどをふらっとにたもつ" },
  { text: "リターンキーは小指で押す", romaji: "りたーんきーはこゆびでおす" },
  { text: "スペースは両親指で叩く", romaji: "すぺーすはりょうおやゆびでたたく" },
  { text: "ミスタイプはすぐ直す", romaji: "みすたいぷはすぐなおす" },
  { text: "気持ちの余裕が精度を上げる", romaji: "きもちのよゆうがせいどをあげる" },
  { text: "文節で区切って入力する", romaji: "ぶんせつできってにゅうりょくする" },
  { text: "口ずさみながらタイピング", romaji: "くちずさみながらたいぴんぐ" },
  { text: "指先の音を揃えてみる", romaji: "ゆびさきのおとをそろえてみる" },
  { text: "疲れを感じたら手を振る", romaji: "つかれをかんじたらてをふる" },
  { text: "爪は短めに整える", romaji: "つめはみじかめにととのえる" },
  { text: "姿勢が崩れたら深呼吸", romaji: "しせいがくずれたらしんこきゅう" },
  { text: "慣れてきたら少しずつ加速", romaji: "なれてきたらすこしずつかそく" },
  { text: "ときどき指体操を挟む", romaji: "ときどきゆびたいそうをはさむ" },
  { text: "画面は目線より少し下", romaji: "がめんはめせんよりすこしした" },
  { text: "呼吸を止めずリズムを刻む", romaji: "こきゅうをとめずりずむをきざむ" },
  { text: "キー配置を眺めて記憶する", romaji: "きーはいちをながめてきおくする" },
  { text: "ショートカットを一日一個覚える", romaji: "しょーとかっとをいちにちいっこおぼえる" },
  { text: "誤入力の癖をメモして直す", romaji: "ごにゅうりょくのくせをめもしてなおす" },
  { text: "打ちにくい単語を練習する", romaji: "うちにくいたんごをれんしゅうする" },
  { text: "ホームポジションへ必ず戻る", romaji: "ほーむぽじしょんへかならずもどる" },
  { text: "同じ文字を連打しない", romaji: "おなじもじをれんだしない" },
  { text: "視線移動を最小限にする", romaji: "しせんいどうをさいしょうげんにする" },
  { text: "指番号を意識して打つ", romaji: "ゆびばんごうをいしきしてうつ" },
  { text: "キーを押し込みすぎない", romaji: "きをおしこみすぎない" },
  { text: "ゆっくりでも正確に刻む", romaji: "ゆっくりでもせいかくにきざむ" },
  { text: "手を温めてから始める", romaji: "てをあたためてからはじめる" },
  { text: "手首を台に乗せすぎない", romaji: "てくびをだいにのせすぎない" },
  { text: "休憩中は目を遠くに向ける", romaji: "きゅうけいちゅうはめをとおくにむける" },
  { text: "画面を明るすぎにしない", romaji: "がめんをあかるすぎにしない" },
  { text: "入力前に意味を理解する", romaji: "にゅうりょくまえにいみをりかいする" },
  { text: "小さな達成を喜ぶ", romaji: "ちいさなたっせいをよろこぶ" },
  { text: "姿勢とリズムをセットで意識", romaji: "しせいとりずむをせっとでいしき" },
  { text: "呼吸と打鍵をシンクロさせる", romaji: "こきゅうとだけんをしんくろさせる" },
  { text: "机の上を整えてから始める", romaji: "つくえのうえをととのえてからはじめる" },
  { text: "入力ログを振り返る", romaji: "にゅうりょくろぐをふりかえる" },
  { text: "手順を声に出しながら打つ", romaji: "てじゅんをこえにだしながらうつ" },
  { text: "五感を使ってリズムを刻む", romaji: "ごかんをつかってりずむをきざむ" },
  { text: "手元の力みを都度確認", romaji: "てもとのりきみをつどかくにん" },
  { text: "肩甲骨を寄せて背筋を伸ばす", romaji: "けんこうこつをよせてせすじをのばす" },
  { text: "姿勢チェックの付箋を貼る", romaji: "しせいちぇっくのふせんをはる" },
  { text: "手元ライトは柔らかい光で", romaji: "てもとらいとはやわらかいひかりで" },
  { text: "リズムに乗ればミスが減る", romaji: "りずむにのればみすがへる" },
  { text: "肩をすくめずリラックス", romaji: "かたをすくめずりらっくす" },
  { text: "タイムより安定感を優先", romaji: "たいむよりあんていかんをゆうせん" },
  { text: "足裏を床につけて踏ん張る", romaji: "あしうらをゆかにつけてふんばる" },
  { text: "ひざは直角を意識する", romaji: "ひざはちょっかくをいしきする" },
  { text: "椅子の高さをこぶし一つ分下げる", romaji: "いすのたかさをこぶしひとつぶんさげる" },
  { text: "肩を回して力みを抜く", romaji: "かたをまわしてりきみをぬく" },
  { text: "指先を軽く弾くように打つ", romaji: "ゆびさきをかるくはじくようにうつ" },
  { text: "打鍵前に一呼吸おく", romaji: "だけんまえにひとこきゅうおく" },
  { text: "ブラインドタッチを信じる", romaji: "ぶらいんどたっちをしんじる" },
  { text: "入力後すぐホームに戻る", romaji: "にゅうりょくごすぐほーむにもどる" },
  { text: "背中を反らせずまっすぐ", romaji: "せなかをそらせずまっすぐ" },
  { text: "肩幅くらいに肘を開く", romaji: "かたはばくらいにひじをひらく" },
  { text: "打ちやすい高さにモニタを置く", romaji: "うちやすいたかさにもにたをおく" },
  { text: "画面まで腕一本分離す", romaji: "がめんまでうでいっぽんぶんはなす" },
  { text: "定期的に首を回す", romaji: "ていきてきにくびをまわす" },
  { text: "深く座りすぎない", romaji: "ふかくすわりすぎない" },
  { text: "指先を温めてから始める", romaji: "ゆびさきをあたためてからはじめる" },
  { text: "手首を支えず空中で保つ", romaji: "てくびをささえずくうちゅうでたもつ" },
  { text: "小指の可動域を広げる", romaji: "こゆびのかどういきをひろげる" },
  { text: "母音を意識してリズムを揃える", romaji: "ぼいんをいしきしてりずむをそろえる" },
  { text: "濁音と半濁音を正確に打つ", romaji: "だくおんとはんだくおんをせいかくにうつ" },
  { text: "小さいつの入力を丁寧に", romaji: "ちいさいつのにゅうりょくをていねいに" },
  { text: "長音記号の場所を確認", romaji: "ちょうおんきごうのばしょをかくにん" },
  { text: "数字は上段を優先して使う", romaji: "すうじはじょうだんをゆうせんしてつかう" },
  { text: "記号キーの位置を暗記する", romaji: "きごうきーのいちをあんきする" },
  { text: "左右のバランスよく打つ", romaji: "さゆうのばらんすよくうつ" },
  { text: "苦手キーを重点練習する", romaji: "にがてきをじゅうてんれんしゅうする" },
  { text: "入力ペースを声に出して数える", romaji: "にゅうりょくぺーすをこえにだしてかぞえる" },
  { text: "目を閉じてホームポジション確認", romaji: "めをとじてほーむぽじしょんかくにん" },
  { text: "打ちやすい指の角度を探す", romaji: "うちやすいゆびのかくどをさがす" },
  { text: "腕を机に預けすぎない", romaji: "うでをつくえにあずけすぎない" },
  { text: "指の動きを最小限にする", romaji: "ゆびのうごきをさいしょうげんにする" },
  { text: "一文ごとに小休止する", romaji: "いちぶんごとにしょうきゅうしする" },
  { text: "肩の高さを左右で揃える", romaji: "かたのたかさをさゆうでそろえる" },
  { text: "机上の物を減らして視野を広げる", romaji: "きじょうのものをへらしてしやをひろげる" },
  { text: "二本指でスペースを叩かない", romaji: "にほんゆびですぺーすをたたかない" },
  { text: "右手ばかりに頼らない", romaji: "みぎてばかりにたよらない" },
  { text: "左手の小指を意識する", romaji: "ひだりてのこゆびをいしきする" },
  { text: "姿勢が崩れたら即修正", romaji: "しせいがくずれたらそくしゅうせい" },
  { text: "入力中も呼吸を忘れない", romaji: "にゅうりょくちゅうもこきゅうをわすれない" },
  { text: "背筋を伸ばして骨盤を立てる", romaji: "せすじをのばしてこつばんをたてる" },
  { text: "打鍵に力を入れすぎない", romaji: "だけんにちからをいれすぎない" },
  { text: "モニタは真正面に置く", romaji: "もにたはましょうめんにおく" },
  { text: "椅子に深く座りすぎない", romaji: "いすにふかくすわりすぎない" },
  { text: "足を組まず安定させる", romaji: "あしをくまずあんていさせる" },
  { text: "手汗をこまめに拭き取る", romaji: "てあせをこまめにふきとる" },
  { text: "小休止で手をぶらぶらさせる", romaji: "しょうきゅうしでてをぶらぶらさせる" },
  { text: "長時間は無理せず区切る", romaji: "ちょうじかんはむりせずくぎる" },
  { text: "指の可動域を広げておく", romaji: "ゆびのかどういきをひろげておく" },
  { text: "キーの段差を意識して触る", romaji: "きーのだんさをいしきしてさわる" },
  { text: "ひらがな配列も試してみる", romaji: "ひらがなはいれつもためしてみる" },
  { text: "数字入力は目で確認してから", romaji: "すうじにゅうりょくはめでかくにんしてから" },
  { text: "指の上下移動を小さく", romaji: "ゆびのじょうげいどうをちいさく" },
  { text: "キー音を一定に保つ", romaji: "きーおんをいっていにたもつ" },
  { text: "打鍵前に姿勢をリセット", romaji: "だけんまえにしせいをりせっと" },
  { text: "目線を落とさず前を向く", romaji: "めせんをおとさずまえをむく" },
  { text: "集中が切れたら歩いてくる", romaji: "しゅうちゅうがきれたらあるいてくる" },
  { text: "目の乾燥に注意する", romaji: "めのかんそうにちゅういする" },
  { text: "眼球運動でリフレッシュ", romaji: "がんきゅううんどうでりふれっしゅ" },
  { text: "キーボードの角度を調整", romaji: "きーぼーどのかくどをちょうせい" },
  { text: "照明の反射を避ける", romaji: "しょうめいのはんしゃをさける" },
  { text: "腕時計を外して軽くする", romaji: "うでどけいをはずしてかるくする" },
  { text: "リングなどを外しておく", romaji: "りんぐなどをはずしておく" },
  { text: "打つ前に手をすり合わせる", romaji: "うつまえにてをすりあわせる" },
  { text: "腱鞘炎を防ぐため無理しない", romaji: "けんしょうえんをふせぐためむりしない" },
  { text: "座面を少し前下がりにする", romaji: "ざめんをすこしまえさがりにする" },
  { text: "肩幅より少し広めに肘を置く", romaji: "かたはばよりすこしひろめにひじをおく" },
  { text: "体を左右に揺らして力を抜く", romaji: "からだをさゆうにゆらしてちからをぬく" },
  { text: "数字キーはホームから伸ばす", romaji: "すうじきーはほーむからのばす" },
  { text: "無理なストレッチは避ける", romaji: "むりなすとれっちはさける" },
  { text: "足首を回して血流を促す", romaji: "あしくびをまわしてけつりゅうをうながす" },
  { text: "手を握ったり開いたりする", romaji: "てをにぎったりひらいたりする" },
  { text: "肩をすくめて脱力チェック", romaji: "かたをすくめてだつりょくちぇっく" },
  { text: "背中を丸めず呼吸を通す", romaji: "せなかをまるめずこきゅうをとおす" },
  { text: "椅子の座面に深く座らない", romaji: "いすのざめんにふかくすわらない" },
  { text: "口角を上げてリラックス", romaji: "こうかくをあげてりらっくす" },
  { text: "肩を上下にすばやく揺らす", romaji: "かたをじょうげにはやくゆらす" },
  { text: "タイピングはスポーツに似ている", romaji: "たいぴんぐはすぽーつににている" },
  { text: "結果よりプロセスを楽しむ", romaji: "けっかよりぷろせすをたのしむ" },
  { text: "短い目標を積み重ねる", romaji: "みじかいもくひょうをつみかさねる" },
  { text: "音のリズムを意識して打つ", romaji: "おとのりずむをいしきしてうつ" },
  { text: "キーの重さを感じ取る", romaji: "きーのおもさをかんじとる" },
  { text: "ミスを恐れず挑戦する", romaji: "みすをおそれずちょうせんする" },
  { text: "疲れたらストレッチ", romaji: "つかれたらすとれっち" },
  { text: "姿勢が崩れたら椅子を調整", romaji: "しせいがくずれたいすをちょうせい" },
  { text: "目の高さに合わせて画面を置く", romaji: "めのたかさにあわせてがめんをおく" },
  { text: "音読して指を動かす", romaji: "おんどくしてゆびをうごかす" },
  { text: "意識してゆっくり打つ", romaji: "いしきしてゆっくりうつ" },
  { text: "いつもの癖をメモする", romaji: "いつものくせをめもする" },
  { text: "高頻度の単語を練習する", romaji: "こうひんどのたんごをれんしゅうする" },
  { text: "片手練習で弱点を補う", romaji: "かたてれんしゅうでじゃくてんをおぎなう" },
  { text: "手を大きく振って血流アップ", romaji: "てをおおきくふってけつりゅうあっぷ" },
  { text: "姿勢写真を撮って確認する", romaji: "しせいしゃしんをとってかくにんする" },
  { text: "机の奥行きを調整する", romaji: "つくえのおくゆきをちょうせいする" },
  { text: "指番号を声に出して覚える", romaji: "ゆびばんごうをこえにだしておぼえる" },
  { text: "休憩時は立ち上がる", romaji: "きゅうけいじはたちあがる" },
  { text: "肩をすくめてから脱力", romaji: "かたをすくめてからだつりょく" },
  { text: "モニタの角度を少し傾ける", romaji: "もにたのかくどをすこしかたむける" },
  { text: "眼鏡の位置を整える", romaji: "めがねのいちをととのえる" },
  { text: "照明のちらつきを避ける", romaji: "しょうめいのちらつきをさける" },
  { text: "椅子を少し前に出す", romaji: "いすをすこしまえにだす" },
  { text: "手のひらをほぐす", romaji: "てのひらをほぐす" },
  { text: "親指の付け根を伸ばす", romaji: "おやゆびのつけねをのばす" },
  { text: "肩の位置を左右で揃える", romaji: "かたのいちをさゆうでそろえる" },
  { text: "足首を上下に動かす", romaji: "あしくびをじょうげにうごかす" },
  { text: "椅子の背に軽く触れる程度", romaji: "いすのせにかるくふれるていど" },
  { text: "背筋を伸ばして息を吸う", romaji: "せすじをのばしていきをすう" },
  { text: "吐く息で力を抜く", romaji: "はくいきでちからをぬく" },
  { text: "肩を下げて首を長くする", romaji: "かたをさげてくびをながくする" },
  { text: "左右の小指を均等に使う", romaji: "さゆうのこゆびをきんとうにつかう" },
  { text: "打鍵前に手を前後に振る", romaji: "だけんまえにてをぜんごにふる" },
  { text: "手を膝に置いて休ませる", romaji: "てをひざにおいてやすませる" },
  { text: "椅子の高さを日々見直す", romaji: "いすのたかさをひびみなおす" },
  { text: "机下の足置きを使う", romaji: "つくえしたのあしおきをつかう" },
  { text: "親指の位置を一定に保つ", romaji: "おやゆびのいちをいっていにたもつ" },
  { text: "打鍵のたびに肩をすくめない", romaji: "だけんのたびにかたをすくめない" },
  { text: "指を伸ばしすぎない", romaji: "ゆびをのばしすぎない" },
  { text: "姿勢のチェックリストを作る", romaji: "しせいのちぇっくりすとをつくる" },
  { text: "首を左右に傾けてほぐす", romaji: "くびをさゆうにかたむけてほぐす" },
  { text: "肩を前後に回す", romaji: "かたをぜんごにまわす" },
  { text: "リラックス用の音楽を流す", romaji: "りらっくすようのおんがくをながす" },
  { text: "机の天板をきれいにする", romaji: "つくえのてんばんをきれいにする" },
  { text: "手元を温めるカイロを使う", romaji: "てもとをあたためるかいろをつかう" },
  { text: "頬杖をつかない", romaji: "ほおづえをつかない" },
  { text: "姿勢アプリで確認する", romaji: "しせいあぷりでかくにんする" },
  { text: "机の高さをメモしておく", romaji: "つくえのたかさをめもしておく" },
  { text: "肘を広げすぎない", romaji: "ひじをひろげすぎない" },
  { text: "肩と耳の距離を意識", romaji: "かたとみみのきょりをいしき" },
  { text: "足裏全体で床を押す", romaji: "あしうらぜんたいでゆかをおす" },
  { text: "椅子のキャスターの動きを確認", romaji: "いすのきゃすたーのうごきをかくにん" },
  { text: "足を組む癖をやめる", romaji: "あしをくむくせをやめる" },
  { text: "肩甲骨を寄せて胸を開く", romaji: "けんこうこつをよせてむねをひらく" },
  { text: "深呼吸で視界をクリアにする", romaji: "しんこきゅうでしかいをくりあにする" },
  { text: "頸椎を伸ばす意識を持つ", romaji: "けいついをのばすいしきをもつ" },
  { text: "膝が机に当たらない位置にする", romaji: "ひざがつくえにあたらないいちにする" },
  { text: "画面の輝度を適切に保つ", romaji: "がめんのきどをてきせつにたもつ" },
  { text: "ブルーライトを調整する", romaji: "ぶるーらいとをちょうせいする" },
  { text: "背筋を伸ばして打鍵する", romaji: "せすじをのばしてだけんする" },
  { text: "キーの中心を意識して押す", romaji: "きーのちゅうしんをいしきしておす" },
  { text: "スペースの連打を避ける", romaji: "すぺーすのれんだをさける" },
  { text: "肩を落として耳から離す", romaji: "かたをおとしてみみからはなす" },
  { text: "息を吐きながら打つ", romaji: "いきをはきながらうつ" },
  { text: "吸う息で背筋を伸ばす", romaji: "すういきでせすじをのばす" },
  { text: "膝を直角に保つ", romaji: "ひざをちょっかくにたもつ" },
  { text: "足を床にしっかり付ける", romaji: "あしをゆかにしっかりつける" },
  { text: "椅子と机の距離を一定にする", romaji: "いすとつくえのきょりをいっていにする" },
  { text: "肩の上がり下がりをチェック", romaji: "かたのあがりさがりをちぇっく" },
  { text: "目薬で乾燥を防ぐ", romaji: "めぐすりでかんそうをふせぐ" },
  { text: "フットレストを活用する", romaji: "ふっとれすとをかつようする" },
  { text: "座布団で高さを微調整する", romaji: "ざぶとんでたかさをびちょうせいする" },
  { text: "手元を照らすライトを置く", romaji: "てもとをてらすらいとをおく" },
  { text: "目線をキーボードに落とさない", romaji: "めせんをきーぼーどにおとさない" },
  { text: "肩を回して血行を促す", romaji: "かたをまわしてけっこうをうながす" },
  { text: "目を閉じて数秒休む", romaji: "めをとじてすうびょうやすむ" },
  { text: "肩と腰のラインを揃える", romaji: "かたとこしのらいんをそろえる" },
  { text: "キートップを優しく押す", romaji: "きーとっぷをやさしくおす" },
  { text: "エンターキーは小指で押す", romaji: "えんたーきーはこゆびでおす" },
  { text: "片手に頼らず両手を使う", romaji: "かたてにたよらずりょうてをつかう" },
  { text: "背筋を伸ばし顎を引く", romaji: "せすじをのばしあごをひく" },
  { text: "肩を寄せて胸を開く", romaji: "かたをよせてむねをひらく" },
  { text: "足の裏を感じながら座る", romaji: "あしのうらをかんじながらすわる" },
  { text: "肩と肘の角度を意識する", romaji: "かたとひじのかくどをいしきする" },
  { text: "指を揃えてホームに戻る", romaji: "ゆびをそろえてほーむにもどる" },
  { text: "机の角に肘を当てない", romaji: "つくえのかどにひじをあてない" },
  { text: "伸びをして体をほぐす", romaji: "のびをしてからだをほぐす" },
  { text: "首のストレッチをする", romaji: "くびのすとれっちをする" },
  { text: "目の奥を休ませる", romaji: "めのおくをやすませる" },
  { text: "座面の奥行きを調整する", romaji: "ざめんのおくゆきをちょうせいする" },
  { text: "姿勢が整ったら打鍵開始", romaji: "しせいがととのったらだけんかいし" },
  { text: "靴の締め付けをゆるめる", romaji: "くつのしめつけをゆるめる" },
  { text: "手の甲を軽くたたいて血行促進", romaji: "てのこうをかるくたたいてけっこうそくしん" },
  { text: "肩を上げ下げして温める", romaji: "かたをあげさげしてあたためる" },
  { text: "膝が外向きにならないように", romaji: "ひざがそとむきにならないように" },
  { text: "親指の付け根を揉む", romaji: "おやゆびのつけねをもむ" },
  { text: "指の第一関節をほぐす", romaji: "ゆびのだいいちかんせつをほぐす" },
  { text: "目の周りを温める", romaji: "めのまわりをあたためる" },
  { text: "長文は声に出しながら入力", romaji: "ちょうぶんはこえにだしながらにゅうりょく" },
  { text: "姿勢維持にクッションを使う", romaji: "しせいいじにくっしょんをつかう" },
  { text: "腰に力を入れすぎない", romaji: "こしにちからをいれすぎない" },
  { text: "肩の位置を鏡で確認する", romaji: "かたのいちをかがみでかくにんする" },
  { text: "ハンドクリームで滑りを調整", romaji: "はんどくりーむですべりをちょうせい" },
  { text: "目を閉じて深呼吸三回", romaji: "めをとじてしんこきゅうさんかい" },
  { text: "椅子の高さを定期的に再確認", romaji: "いすのたかさをていきてきにさいかくにん" },
  { text: "背筋が丸まらないよう注意", romaji: "せすじがまるまらないようちゅうい" },
  { text: "指の独立を意識する", romaji: "ゆびのどくりつをいしきする" },
  { text: "手の甲を上げすぎない", romaji: "てのこうをあげすぎない" },
  { text: "足の位置を固定する", romaji: "あしのいちをこていする" },
  { text: "モニタの高さを本で調整", romaji: "もにたのたかさをほんでちょうせい" },
  { text: "首を前に出しすぎない", romaji: "くびをまえにだしすぎない" },
  { text: "肩をすくめず耳から離す", romaji: "かたをすくめずみみからはなす" },
  { text: "視野を広くとって画面を見る", romaji: "しやをひろくとってがめんをみる" },
  { text: "数分おきに姿勢を整える", romaji: "すうふんおきにしせいをととのえる" },
  { text: "キーボードを少し手前に置く", romaji: "きーぼーどをすこしてまえにおく" },
  { text: "力まずにキーを撫でるように打つ", romaji: "りきまずにきをなでるようにうつ" },
  { text: "身体を左右に軽くひねる", romaji: "からだをさゆうにかるくひねる" },
  { text: "指先を机にトントンして温める", romaji: "ゆびさきをつくえにとんとんしてあたためる" },
  { text: "打鍵リズムをメトロノームで確認", romaji: "だけんりずむをめとろのーむでかくにん" },
  { text: "疲れたら目を閉じ深呼吸", romaji: "つかれたらめをとじしんこきゅう" },
  { text: "肩と腰を一直線に保つ", romaji: "かたとこしをいっちょくせんにたもつ" },
  { text: "脚を組み替えて座らない", romaji: "あしをくみかえてすわらない" },
  { text: "肩を寄せず開きすぎず", romaji: "かたをよせずひらきすぎず" },
  { text: "手の甲を机に置かない", romaji: "てのこうをつくえにおかない" },
  { text: "リズムを口で数えながら打つ", romaji: "りずむをくちでかぞえながらうつ" },
  { text: "モニタの位置を毎回確認する", romaji: "もにたのいちをまいかいかくにんする" },
  { text: "肩が上がっていないか意識する", romaji: "かたがあがっていないかいしきする" },
  { text: "足を前後にずらして安定を取る", romaji: "あしをぜんごにずらしてあんていをとる" },
  { text: "首をゆっくり左右に回す", romaji: "くびをゆっくりさゆうにまわす" },
  { text: "指先の温度を感じる", romaji: "ゆびさきのおんどをかんじる" },
  { text: "手の甲をさすって血行を促す", romaji: "てのこうをさすってけっこうをうながす" },
  { text: "肩甲骨を広げて胸を開く", romaji: "けんこうこつをひろげてむねをひらく" },
  { text: "膝が内側に入らないように", romaji: "ひざがうちがわにはいらないように" },
  { text: "顎を引いて首をまっすぐにする", romaji: "あごをひいてくびをまっすぐにする" },
  { text: "目線を画面中央に合わせる", romaji: "めせんをがめんちゅうおうにあわせる" },
  { text: "まばたきを忘れない", romaji: "まばたきをわすれない" },
  { text: "椅子の背もたれは軽く触れるだけ", romaji: "いすのせもたれはかるくふれるだけ" },
  { text: "肩を寄せず開きすぎず中庸に", romaji: "かたをよせずひらきすぎずちゅうように" },
  { text: "指を伸ばしすぎず丸めすぎず", romaji: "ゆびをのばしすぎずまるめすぎず" },
  { text: "ホームポジションを再確認する", romaji: "ほーむぽじしょんをさいかくにんする" },
  { text: "小休止で立ち上がり伸びをする", romaji: "しょうきゅうしでたちあがりのびをする" },
  { text: "視線を遠くに移し目を休める", romaji: "しせんをとおくにうつしめをやすめる" },
  { text: "肩の力みを息で流す", romaji: "かたのりきみをいきでながす" },
  { text: "背筋が丸まったら胸を開く", romaji: "せすじがまるまったらむねをひらく" },
  { text: "腕を大きく回して血流を促す", romaji: "うでをおおきくまわしてけつりゅうをうながす" },
  { text: "打鍵の強弱を揃える", romaji: "だけんのきょうじゃくをそろえる" },
  { text: "キーボードの傾きを一定にする", romaji: "きーぼーどのかたむきをいっていにする" },
  { text: "キーの中心を狙って押す", romaji: "きーのちゅうしんをねらっておす" },
  { text: "姿勢が楽な位置で椅子を固定", romaji: "しせいがらくないちでいすをこてい" },
  { text: "無理に速く打とうとしない", romaji: "むりにはやくうとうとしない" },
  { text: "音のリズムで速度を管理する", romaji: "おとのりずむでそくどをかんりする" },
  { text: "姿勢を戻す合図を決める", romaji: "しせいをもどすあいずをきめる" },
  { text: "手元を温める飲み物を用意", romaji: "てもとをあたためるのみものをようい" },
  { text: "リラックスして肩を落とす", romaji: "りらっくすしてかたをおとす" },
  { text: "机の高さをメモに残す", romaji: "つくえのたかさをめもにのこす" },
  { text: "光量を下げて目を守る", romaji: "こうりょうをさげてめをまもる" },
  { text: "打鍵のリズムを心で数える", romaji: "だけんのりずむをこころでかぞえる" },
  { text: "キートップの摩耗を確認", romaji: "きーとっぷのまもうをかくにん" },
  { text: "定期的にキーボードを掃除", romaji: "ていきてきにきーぼーどをそうじ" },
];

export const LOCAL_TEXT_GROUPS: Issue[][] = [EN_SHORT, JA_SHORT];

// 長文モード（英語＋日本語ひらがな読み）既存のまま
export const LONG_TEXT_ISSUES: Issue[] = [
  {
    text: "Typing long paragraphs smoothly requires steady rhythm and relaxed shoulders. Focus on accuracy first, speed will follow.",
    romaji:
      "Typing long paragraphs smoothly requires steady rhythm and relaxed shoulders. Focus on accuracy first, speed will follow.",
  },
  {
    text: "Consistency beats bursts. Daily five minute sessions build stronger muscle memory than a single marathon practice on the weekend.",
    romaji:
      "Consistency beats bursts. Daily five minute sessions build stronger muscle memory than a single marathon practice on the weekend.",
  },
  {
    text: "Good posture, proper desk height, and short breaks prevent fatigue. Comfort is part of performance.",
    romaji:
      "Good posture, proper desk height, and short breaks prevent fatigue. Comfort is part of performance.",
  },
  {
    text: "When copying code, read for meaning before you type. Understanding structure reduces mistakes and improves retention.",
    romaji:
      "When copying code, read for meaning before you type. Understanding structure reduces mistakes and improves retention.",
  },
  {
    text: "Rapid iteration beats premature optimization. Ship small improvements, measure, and adjust quickly.",
    romaji:
      "Rapid iteration beats premature optimization. Ship small improvements, measure, and adjust quickly.",
  },
  {
    text: "Copy what you understand. Typing is faster when your brain is ahead of your fingers.",
    romaji: "Copy what you understand. Typing is faster when your brain is ahead of your fingers.",
  },
  {
    text: "Celebrate small wins. Each error free sentence is a clear signal that your practice is working.",
    romaji:
      "Celebrate small wins. Each error free sentence is a clear signal that your practice is working.",
  },
  // ここから日本語長文（漢字交じり、romajiはひらがな読み）

  {
    text: "タイピングの上達には毎日の積み重ねが欠かせません。短い時間でも続けることで指が自然に動くようになります。",
    romaji:
      "たいぴんぐのじょうたつにはまいにちのつみかさねがかかせません。みじかいじかんでもつづけることでゆびがしぜんにうごくようになります。",
  },
  {
    text: "正しい姿勢とリズムで練習すると疲れにくく、集中力も長続きします。肩の力を抜いて深呼吸してからキーを打ちましょう。",
    romaji:
      "ただしいしせいとりずむでれんしゅうするとつかれにくく、しゅうちゅうりょくもながつづきします。かたのちからをぬいてしんこきゅうしてからきーをうちましょう。",
  },
  {
    text: "文章の意味を理解してから入力すると、覚えやすくミスも減ります。まず一度読んで内容をつかんでから指を動かしましょう。",
    romaji:
      "ぶんしょうのいみをりかいしてからにゅうりょくすると、おぼえやすくみすもへります。まずいちどよんでないようをつかんでからゆびをうごかしましょう。",
  },
  {
    text: "長い文章を速く正確に打つには、先に内容を理解し、文節ごとに区切ってリズムを作ることが大切です。画面から目を離さず、肩の力を抜いて一定のテンポで打鍵しましょう。",
    romaji:
      "ながいぶんしょうをはやくせいかくにうつには、さきにないようをりかいし、ぶんせつごとにくぎってりずむをつくることがたいせつです。がめんからめをはなさず、かたのちからをぬいていっていのてんぽでだけんしましょう。",
  },
  {
    text: "正しい姿勢で座り、手首を浮かせてホームポジションに指を置けば、無駄な動きが減って疲労も少なくなります。難しい漢字が出ても慌てず、一文字ずつ丁寧に入力してください。",
    romaji:
      "ただしいしせいですわり、てくびをうかせてほーむぽじしょんにゆびをおけば、むだなうごきがへってひろうもすくなくなります。むずかしいかんじがでてもあわてず、ひともじずつていねいににゅうりょくしてください。",
  },
  {
    text: "肩こりを防ぐためには、十分な休憩と軽いストレッチが欠かせません。息を吸って吐き、視線を遠くに移してから再びキーボードに向き合うと集中力が長続きします。",
    romaji:
      "かたこりをふせぐためには、じゅうぶんなきゅうけいとかるいすとれっちがかかせません。いきをすってはき、しせんをとおくにうつしてからふたたびきーぼーどにむきあうとしゅうちゅうりょくがながつづきします。",
  },
  {
    text: "指先の感覚が鈍ってきたら、一度手を温めてから再開するとミスが減ります。手のひらをこすり合わせ、軽く握ったり開いたりして血行を促しましょう。",
    romaji:
      "ゆびさきのかんかくがにぶってきたら、いちどてをあたためてからさいかいするとみすがへります。てのひらをこすりあわせ、かるくにぎったりひらいたりしてけっこうをうながしましょう。",
  },
  {
    text: "長時間の練習では、椅子の高さや画面の角度を定期的に見直すと姿勢が安定します。足裏を床にしっかりつけ、膝を直角に保ち、背筋を伸ばしましょう。",
    romaji:
      "ちょうじかんのれんしゅうでは、いすのたかさやがめんのかくどをていきてきにみなおすとしせいがあんていします。あしうらをゆかにしっかりつけ、ひざをちょっかくにたもち、せすじをのばしましょう。",
  },
  {
    text: "深呼吸して肩の力を抜き、一定のテンポで打鍵するとリズムが保たれます。焦らず落ち着いて一行ずつ進めてください。",
    romaji:
      "しんこきゅうしてかたのちからをぬき、いっていのてんぽでだけんするとりずむがたもたれます。あせらずおちついていちぎょうずつすすめてください。",
  },
  {
    text: "目線は画面中央に置き、手元は見ずにキー配置を体で覚えましょう。視線移動が減るほど入力は安定します。",
    romaji:
      "めせんはがめんちゅうおうにおき、てもとはみずにきーはいちをからだでおぼえましょう。しせんいどうがへるほどにゅうりょくはあんていします。",
  },
  {
    text: "スペースとシフトの親指運用を意識すると手の負担が軽くなります。左右の親指を交互に使うとバランスが取れます。",
    romaji:
      "すぺーすとしふとのおやゆびうんようをいしきするとてのふたんがかるくなります。さゆうのおやゆびをこうごに使うとばらんすがとれます。",
  },
  {
    text: "難しい漢字や記号が出ても慌てず、一文字ずつ丁寧に置いていきましょう。精度が上がれば自然と速度も伸びます。",
    romaji:
      "むずかしいかんじやきごうがでてもあわてず、ひともじずつていねいにおいていきましょう。せいどがあがればしぜんとそくどものびます。",
  },
  {
    text: "適度な水分補給と休憩が長時間のタイピングを支えます。目を休めてから再開するとミスが減ります。",
    romaji:
      "てきどなすいぶんほきゅうときゅうけいがちょうじかんのたいぴんぐをささえます。めをやすめてからさいかいするとみすがへります。",
  },
  {
    text: "打鍵音を揃える意識を持つと、安定した入力が身につきます。一定のリズムで軽く叩くようにしましょう。",
    romaji:
      "だけんおんをそろえるいしきをもつと、あんていしたにゅうりょくがみにつきます。いっていのりずむでかるくたたくようにしましょう。",
  },
  {
    text: "手首を台に預けすぎず、肘と肩の角度を直角に近づけると疲労が減ります。腕全体をリラックスさせてください。",
    romaji:
      "てくびをだいにあずけすぎず、ひじとかたのかくどをちょっかくにちかづけるとひろうがへります。うでぜんたいをりらっくすさせてください。",
  },
  {
    text: "ブラインドタッチの練習は短時間でも毎日続けると効果的です。指の位置を体に染み込ませましょう。",
    romaji:
      "ぶらいんどたっちのれんしゅうはたんじかんでもまいにちつづけるとこうかてきです。ゆびのいちをからだにしみこませましょう。",
  },
  {
    text: "文章を声に出して読みながら打つと、内容理解とリズムが一致しやすくなります。リズムが崩れたら一旦深呼吸しましょう。",
    romaji:
      "ぶんしょうをこえにだしてよみながらうつと、ないようりかいとりずむがいっちしやすくなります。りずむがくずれたらいったんしんこきゅうしましょう。",
  },
  {
    text: "小指や薬指を意識的に使って左右のバランスを整えましょう。弱い指を鍛えると全体の速度が上がります。",
    romaji:
      "こゆびやくすりゆびをいしきてきにつかってさゆうのばらんすをととのえましょう。よわいゆびをきたえるとぜんたいのそくどがあがります。",
  },
  {
    text: "モニターの高さを目線よりやや下にすると首への負担が減ります。画面は腕一本分ほど離して設置しましょう。",
    romaji:
      "もにたーのたかさをめせんよりややしたにするとくびへのふたんがへります。がめんはうでいっぽんぶんほどはなしてせっちしましょう。",
  },
  {
    text: "目が疲れたら遠くを見てピントをリセットしてください。まばたきを意識するとドライアイを防げます。",
    romaji:
      "めがつかれたらとおくをみてぴんとをりせっとしてください。まばたきをいしきするとどらいあいをふせげます。",
  },
  {
    text: "肩甲骨を動かすストレッチは血行を促し集中力を戻します。大きく肩を回してから再開すると効果的です。",
    romaji:
      "けんこうこつをうごかすすとれっちはけっこうをうながししゅうちゅうりょくをもどします。おおきくかたをまわしてからさいかいするとこうかてきです。",
  },
  {
    text: "手汗が気になるときは軽く拭いてから再開すると滑りが安定します。ハンドクリームは塗りすぎに注意してください。",
    romaji:
      "てあせがきになるときはかるくふいてからさいかいするとすべりがあんていします。はんどくりーむはぬりすぎにちゅういしてください。",
  },
  {
    text: "タイマーを使い二十五分作業と五分休憩を繰り返すと集中を保ちやすくなります。短い休憩で姿勢もリセットしましょう。",
    romaji:
      "たいまーをつかいにじゅうごふんさぎょうとごふんきゅうけいをくりかえすとしゅうちゅうをたもちやすくなります。みじかいきゅうけいでしせいもりせっとしましょう。",
  },
  {
    text: "同じ文章を繰り返し打つとミスタッチの癖が見えてきます。苦手な文字列をメモして重点的に練習しましょう。",
    romaji:
      "おなじぶんしょうをくりかえしうつとみすたっちのくせがみえてきます。にがてなもじれつをめもしてじゅうてんてきにれんしゅうしましょう。",
  },
  {
    text: "入力ログを見返し、誤りが多いキーを集中して練習すると効率的に上達します。小さな改善を積み重ねてください。",
    romaji:
      "にゅうりょくろぐをみかえし、あやまりがおおいきをしゅうちゅうしてれんしゅうするとこうりつてきにじょうたつします。ちいさなかいぜんをつみかさねてください。",
  },
  {
    text: "机と椅子の高さを体格に合わせると打鍵スピードが自然に上がります。足裏をしっかり床につけ、膝は直角を保ちましょう。",
    romaji:
      "つくえといすのたかさをたいかくにあわせるとだけんすぴーどがしぜんにあがります。あしうらをしっかりゆかにつけ、ひざはちょっかくをたもちましょう。",
  },
  {
    text: "肩をすくめないよう意識し、首を長く保つと呼吸がしやすくなります。リラックスした状態が最も速く正確です。",
    romaji:
      "かたをすくめないよういしきし、くびをながくたもつとこきゅうがしやすくなります。りらっくすしたじょうたいがもっともはやくせいかくです。",
  },
  {
    text: "母音の位置を意識すると日本語ローマ字入力の精度が上がります。発音を頭で唱えながら指を動かしましょう。",
    romaji:
      "ぼいんのいちをいしきするとにほんごろーまじにゅうりょくのせいどがあがります。はつおんをあたまでとなえながらゆびをうごかしましょう。",
  },
];

export function getLocalTexts(): Issue[][] {
  return LOCAL_TEXT_GROUPS;
}

export const NUMBER_ISSUES: Issue[] = [
  { text: "1234567890", romaji: "1234567890" },
  { text: "0987654321", romaji: "0987654321" },
  { text: "1122334455", romaji: "1122334455" },
  { text: "3141592653", romaji: "3141592653" },
];
