name: Safe Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint (Biome)
        run: pnpm run lint

      - name: Run type check
        run: pnpm run type-check

      - name: Run tests
        run: pnpm run test
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          NODE_ENV: test
          CI: true

      - name: Build project (Standalone)
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: pnpm run build

      - name: Fix standalone static files and CSS script tag issue
        run: |
          echo "=== Fixing standalone static files and CSS script tag issue ==="

          # Debug: Check current directory and build output
          echo "Current directory: $(pwd)"
          echo "Available files and directories:"
          ls -la

          # Check if .next directory exists
          if [ ! -d ".next" ]; then
            echo "❌ .next directory not found"
            exit 1
          fi

          echo "Contents of .next directory:"
          ls -la .next/

          # Check if standalone build was created
          if [ ! -d ".next/standalone" ]; then
            echo "❌ Standalone build directory not found"
            echo "This might indicate that output: 'standalone' is not properly configured in next.config.ts"
            exit 1
          fi

          echo "✅ Standalone directory found"

          # Copy static files to standalone directory
          if [ -d ".next/static" ]; then
            echo "Copying static files..."
            cp -r .next/static .next/standalone/.next/static
            echo "✅ Static files copied successfully"
            
            # Verify critical files
            if ls .next/standalone/.next/static/css/*.css 1> /dev/null 2>&1; then
              echo "✅ CSS files found"
              echo "CSS files: $(ls .next/standalone/.next/static/css/*.css | wc -l)"
            else
              echo "⚠️ No CSS files found"
            fi
            
            if [ -d ".next/standalone/.next/static/chunks" ]; then
              echo "✅ JavaScript chunks directory found"
              echo "Chunk files: $(ls .next/standalone/.next/static/chunks | wc -l)"
            else
              echo "⚠️ No chunks directory found"
            fi

            # Fix CSS script tag issue in HTML files
            echo "Fixing CSS script tag issue in prerendered HTML files..."
            
            # Find and fix HTML files in standalone build
            find .next/standalone/.next/server/app -name "*.html" -type f 2>/dev/null | while read -r htmlfile; do
              if [ -f "$htmlfile" ]; then
                # Replace CSS script tags with proper link tags
                sed -i 's|<script src="\(/_next/static/css/[^"]*\.css\)" async=""></script>||g' "$htmlfile" 2>/dev/null || true
                echo "Fixed CSS script tags in: $htmlfile"
              fi
            done

            # Also fix in server-side rendered files
            find .next/standalone/.next/server -name "*.js" -type f 2>/dev/null | while read -r jsfile; do
              if [ -f "$jsfile" ] && grep -q "/_next/static/css.*\.css.*async" "$jsfile" 2>/dev/null; then
                # Remove CSS script tag generation from server files
                sed -i 's|src:"/_next/static/css/\([^"]*\.css\)",async:""|rel:"stylesheet",href:"/_next/static/css/\1"|g' "$jsfile" 2>/dev/null || true
                echo "Fixed CSS script generation in: $jsfile"
              fi
            done

            echo "✅ CSS script tag issue fix completed"
            
          else
            echo "❌ Static files directory not found"
            echo "Available directories in .next:"
            ls -la .next/
            exit 1
          fi

      - name: Verify standalone build
        run: |
          echo "=== Verifying standalone build ==="
          if [ -f ".next/standalone/server.js" ]; then
            echo "✅ server.js exists"
          else
            echo "❌ server.js not found"
            exit 1
          fi

          if [ -d ".next/standalone/.next/static" ]; then
            echo "✅ Static directory exists"
            echo "Static files structure:"
            find .next/standalone/.next/static -type d -name "*" | head -20
          else
            echo "❌ Static directory not found"
            exit 1
          fi

          if [ -d ".next/standalone/public" ]; then
            echo "✅ Public directory exists"
          else
            echo "⚠️ Public directory not found, copying..."
            cp -r public .next/standalone/public
            echo "✅ Public directory copied"
          fi

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup production environment
        run: echo "Setting up production environment..."

      - name: Build project (Standalone)
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: pnpm run build

      - name: Prepare standalone deployment
        run: |
          echo "=== Preparing standalone deployment ==="

          # Fix static files
          if [ -d ".next/static" ] && [ -d ".next/standalone" ]; then
            echo "Copying static files to standalone..."
            cp -r .next/static .next/standalone/.next/static
            
            # Copy public directory if not exists
            if [ ! -d ".next/standalone/public" ]; then
              cp -r public .next/standalone/public
            fi
            
            echo "✅ Standalone preparation complete"
          else
            echo "❌ Build directories not found"
            exit 1
          fi

          # Create deployment info
          echo "{
            \"buildId\": \"$(cat .next/BUILD_ID)\",
            \"buildTime\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
            \"gitCommit\": \"${GITHUB_SHA}\",
            \"gitBranch\": \"${GITHUB_REF_NAME}\"
          }" > .next/standalone/deployment-info.json

      - name: Create deployment package
        run: |
          echo "Creating standalone deployment package..."
          cd .next/standalone

          # Create package with all necessary files
          tar -czf ../../deployment-standalone.tar.gz \
            server.js \
            .next/ \
            public/ \
            node_modules/ \
            package.json \
            deployment-info.json || {
              echo "❌ Failed to create deployment package"
              exit 1
            }

          cd ../..
          echo "✅ Package created successfully"
          echo "Package size: $(du -h deployment-standalone.tar.gz)"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat > ~/.ssh/config << EOF
          Host deploy-server
            HostName ${{ secrets.GCP_HOST }}
            User ${{ secrets.GCP_USER }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            ConnectTimeout 30
            ServerAliveInterval 60
            LogLevel ERROR
          EOF
          chmod 600 ~/.ssh/config

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh deploy-server "echo 'SSH connection successful'; uptime; free -h"

      - name: Transfer deployment files
        run: |
          echo "Transferring standalone deployment package..."
          scp deployment-standalone.tar.gz deploy-server:/tmp/

      - name: Deploy standalone application
        timeout-minutes: 15
        run: |
          ssh deploy-server << 'STANDALONE_DEPLOY'
          set -e

          echo "=== Standalone Deployment Process ==="

          # 1. Environment setup
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # 2. Stop existing processes
          echo "Stopping existing processes..."
          pm2 stop all 2>/dev/null || echo "No PM2 processes to stop"
          pm2 delete all 2>/dev/null || echo "No PM2 processes to delete"

          # 3. Backup current deployment
          if [ -d "/var/www/yusuke-kim" ] && [ "$(ls -A /var/www/yusuke-kim 2>/dev/null)" ]; then
            echo "Creating backup..."
            sudo mkdir -p /var/www/backups
            sudo cp -r /var/www/yusuke-kim /var/www/backups/yusuke-kim-$(date +%Y%m%d-%H%M%S)
          fi

          # 4. Prepare deployment directory
          sudo rm -rf /var/www/yusuke-kim/*
          sudo mkdir -p /var/www/yusuke-kim
          sudo chown $USER:www-data /var/www/yusuke-kim
          cd /var/www/yusuke-kim

          # 5. Extract standalone deployment
          tar -xzf /tmp/deployment-standalone.tar.gz

          # 6. Verify deployment
          if [ ! -f "server.js" ] || [ ! -f ".next/BUILD_ID" ]; then
            echo "❌ Deployment verification failed"
            exit 1
          fi

          echo "✅ Files extracted successfully"
          echo "BUILD_ID: $(cat .next/BUILD_ID)"
          echo "Deployment info:"
          cat deployment-info.json

          # 7. Set up environment
          cat > .env.production.local << ENV_EOF
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}
          NODE_ENV=production
          PORT=3000
          ENV_EOF

          # 8. Quick test of standalone server
          echo "Testing standalone server..."
          timeout 30 node server.js &
          TEST_PID=$!

          sleep 15

          if kill -0 $TEST_PID 2>/dev/null; then
            echo "✅ Server startup successful"
            
            # Test endpoints
            if curl -f -s http://localhost:3000/ > /dev/null; then
              echo "✅ Home page responding"
            fi
            
            if curl -f -s http://localhost:3000/api/health > /dev/null; then
              echo "✅ Health check responding"
            fi
            
            kill $TEST_PID
            sleep 3
          else
            echo "❌ Server startup failed"
            exit 1
          fi

          # 9. Start with PM2
          echo "Starting application with PM2..."
          NODE_ENV=production pm2 start server.js --name "yusuke-kim" --env production
          pm2 save
          pm2 startup systemd -u $USER --hp /home/$USER || echo "PM2 startup already configured"

          # 10. Final health check
          sleep 10

          echo "=== Final Health Check ==="
          if pm2 status | grep -q "yusuke-kim.*online"; then
            echo "✅ Application is running"
            
            # Multiple endpoint tests
            ENDPOINTS=("/" "/api/health" "/portfolio/gallery/all" "/_next/static/css/")
            
            for endpoint in "${ENDPOINTS[@]}"; do
              if curl -f -s -o /dev/null -w "%{http_code}" "http://localhost:3000${endpoint}" | grep -q "200\|304"; then
                echo "✅ ${endpoint} - OK"
              else
                echo "⚠️ ${endpoint} - Failed"
              fi
            done
          else
            echo "❌ Application is not running properly"
            pm2 logs yusuke-kim --lines 50
            exit 1
          fi

          echo "=== Deployment completed successfully ==="
          STANDALONE_DEPLOY

      - name: Verify deployment
        run: |
          echo "Waiting for application to stabilize..."
          sleep 15

          echo "Testing production endpoints..."

          # Test main site
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://yusuke-kim.com/)
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "304" ]; then
            echo "✅ Main site is accessible (HTTP $HTTP_CODE)"
          else
            echo "❌ Main site returned HTTP $HTTP_CODE"
            exit 1
          fi

          # Test portfolio page
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://yusuke-kim.com/portfolio/gallery/all)
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "304" ]; then
            echo "✅ Portfolio page is accessible (HTTP $HTTP_CODE)"
          else
            echo "⚠️ Portfolio page returned HTTP $HTTP_CODE"
          fi

      - name: Cleanup
        if: always()
        run: |
          ssh deploy-server << 'CLEANUP'
          # Remove temporary files
          rm -f /tmp/deployment-standalone.tar.gz

          # Clean old backups (keep last 5)
          if [ -d "/var/www/backups" ]; then
            cd /var/www/backups
            ls -t | grep "yusuke-kim-" | tail -n +6 | xargs -r sudo rm -rf
            echo "✅ Old backups cleaned"
          fi
          CLEANUP
